#based https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/wordpress
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.5.18-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
      - ./db-dump:/opt/backup
      - ./db-scripts:/opt/scripts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:6.1.1-php7.4-apache
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8283:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=$DB_HOST
      - WORDPRESS_DB_USER=$DB_USER
      - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      - WORDPRESS_DB_NAME=$DB_NAME
volumes:
  db_data: